server:
  port: 8081

spring:
  application:
    name: fraud-detection-service
  sql:
    init:
      mode: always
  datasource:
    url: jdbc:mysql://localhost:3316/fraud_detection
    username: ${MYSQL_USERNAME:root}
    password: ${MYSQL_PASSWORD:mysql}
    driver-class-name: com.mysql.cj.jdbc.Driver

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics, prometheus
  metrics:
    distribution:
      percentiles-histogram:
        http:
          server:
            requests: true
  observations:
    key-values:
      application: fraud-detection-service
  tracing:
    sampling:
      probability: 1.0
